version: '3'

services:
  node:
    image: node:14.7
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    working_dir: '/app'
    command: 'npm run start:dev'
    networks:
      default:

networks:
  default:
