version: '3'

services:
  node:
    image: node:14.7
    ports:
      - '3000:${APP_PORT}'
    volumes:
      - .:/app
    working_dir: /app
    command: 'npm run start:dev'
    restart: unless-stopped
    depends_on:
      - db
    networks:
      default:
  db:
    image: postgres:13.3
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      TZ: ${TZ}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgres/data
    networks:
      default:
  redis:
    image: redis:6.2.3
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis:/data
    networks: 
      default:

volumes:
  db:
  redis:

networks:
  default:
